baseURL = "https://stuartleeks.com/"
languageCode = "en-us"
title = "stuart leeks"
theme = "stuartleeks1"
# theme = "beautifulhugo"
# theme = "ananke"

[params]
  subtitle = "My little corner of the interwebs"
  mainSections = ["post","posts"]
  rss = true
#   featured_image = "/images/bridge1a.jpg"
  featured_image = "/images/stones1a.jpg"

[Author]
  name = "Stuart Leeks"
  website = "www.stuartleeks.com"
  github = "stuartleeks"
  twitter = "stuartleeks"
  linkedin = "stuartleeks"
  stackoverflow = "users/202415/stuart-leeks"



[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3

[[menu.main]]
    parent = "About"
    name = "me"
    url = "about"
    weight = 1

[[menu.main]]
    parent = "About"
    name = "theme"
    url = "about/theme"
    weight = 3

